;;; -*- lexical-binding: t; -*-
(require 'emacs-ai-terminal)
(defvar workflow-dir (expand-file-name "var/cli-validation/20260908-session-workflow/"))
(defvar workflow-sessions nil)
(defun workflow-snapshot ()
  (dolist (entry workflow-sessions)
    (with-current-buffer (emacs-ai-terminal-output (cdr entry))
      (ghostel--redraw-now (current-buffer) t)
      (let ((coding-system-for-write 'utf-8-unix))
        (write-region (point-min) (point-max)
                      (expand-file-name (concat (car entry) "-screen.txt") workflow-dir) nil 'silent)))))
(defun workflow-key (provider key)
  (with-current-buffer (emacs-ai-terminal-output (cdr (assoc provider workflow-sessions)))
    (emacs-ai-terminal-key key)))
(defun workflow-paste (provider text)
  (with-current-buffer (emacs-ai-terminal-output (cdr (assoc provider workflow-sessions)))
    (ghostel-paste-string text)))
(defun workflow-check-switches ()
  (dotimes (_ 20)
    (dolist (entry workflow-sessions)
      (switch-to-buffer (emacs-ai-terminal-output (cdr entry)))
      (unless (and (eq emacs-ai-terminal--current (cdr entry))
                   (process-live-p (emacs-ai-terminal-process (cdr entry)))
                   emacs-ai-terminal-controls-mode)
        (error "Session switch failed"))))
  (workflow-snapshot)
  (mapcar (lambda (entry)
            (with-current-buffer (emacs-ai-terminal-output (cdr entry))
              (list (car entry) (buffer-name) default-directory
                    (process-id (emacs-ai-terminal-process (cdr entry))))))
          workflow-sessions))
(let* ((base (expand-file-name "var/cli-validation/20260908-korean-path/"))
       (claude-dir (expand-file-name "claude/한글 프로젝트/" base))
       (codex-dir (directory-file-name (expand-file-name "codex/한글 프로젝트/" base))))
  (push (cons "claude" (emacs-ai-terminal-start
                       "Claude workflow" (emacs-ai--executable "claude")
                       '("--permission-mode" "manual" "--resume" "05d64ab8-e453-4511-815f-f78d09a140bf")
                       claude-dir)) workflow-sessions)
  (push (cons "codex" (emacs-ai-terminal-start
                      "Codex workflow" (emacs-ai--executable "codex")
                      (list "resume" "01a07f90-db19-7910-87cd-76a13e97d3f4"
                            "-c" (concat "projects={" (json-encode-string codex-dir) "={trust_level=\"trusted\"}}")
                            "--sandbox" "workspace-write" "--ask-for-approval" "on-request"
                            "-c" "approvals_reviewer=\"user\"") codex-dir)) workflow-sessions))
(set-frame-size (selected-frame) 120 50)
(delete-other-windows)
(with-temp-file (expand-file-name "socket.txt" workflow-dir)
  (insert (expand-file-name server-name server-socket-dir)))
(run-at-time 0 .5 #'workflow-snapshot)
(while t (accept-process-output nil .1))
