;;; eam-session-list.el --- Grouped persistent session list -*- lexical-binding: t; -*-
(require 'eam-terminal)
(require 'eam-persistent)
(require 'eam-notifications)

(defcustom eam-session-sort-order 'activity
  "Initial session list ordering.  Activity means actual PTY input/output."
  :type '(choice (const activity) (const created) (const directory)
                 (const name) (const provider) (const state) (const unread))
  :group 'eam)
(defcustom eam-session-group-by-directory t
  "Group sessions by working directory in the session list."
  :type 'boolean :group 'eam)
(defvar-local eam-session-list--entries nil)
(defvar-local eam-session-list--sort nil)
(defvar-local eam-session-list--group nil)
(defvar-local eam-session-list--detached nil)
(defvar-local eam-session-list--unknown 0)

(defun eam-session-list--at-point ()
  (get-text-property (line-beginning-position) 'eam-session))
(defun eam-session-list--path (entry)
  (alist-get 'session entry))
(defun eam-session-list--directory (entry)
  (directory-file-name (alist-get 'directory entry)))
(defun eam-session-list--time (entry key)
  (let ((value (alist-get key entry))) (if (numberp value) value 0)))
(defun eam-session-list--activity (entry)
  (max (eam-session-list--time entry 'last_input_at)
       (eam-session-list--time entry 'last_output_at)))
(defun eam-session-list--state (entry)
  (if (zerop (or (alist-get 'attached_clients entry) 0)) "detached" "attached"))
(defun eam-session-list--label (entry)
  (let ((name (alist-get 'name entry)))
    (if (and (stringp name) (not (string-empty-p name))) name "(unnamed)")))
(defun eam-session-list--unread (entry)
  (eq t (alist-get 'unread (alist-get 'notifications entry))))
(defun eam-session-list--less (a b)
  "Sort deterministically, with recent activity and stable identity as ties."
  (let* ((key (pcase eam-session-list--sort
                ('created 'created_at) ('directory 'directory)
                ('name 'name) ('provider 'provider) (_ nil)))
         (av (pcase eam-session-list--sort
               ('state (eam-session-list--state a))
               ('unread (if (eam-session-list--unread a) 1 0))
               ('activity (max (eam-session-list--activity a)
                               (eam-session-list--time a 'created_at)))
               (_ (or (alist-get key a) ""))))
         (bv (pcase eam-session-list--sort
               ('state (eam-session-list--state b))
               ('unread (if (eam-session-list--unread b) 1 0))
               ('activity (max (eam-session-list--activity b)
                               (eam-session-list--time b 'created_at)))
               (_ (or (alist-get key b) "")))))
    (if (equal av bv)
        (if (= (eam-session-list--activity a) (eam-session-list--activity b))
            (string< (eam-session-list--path a) (eam-session-list--path b))
          (> (eam-session-list--activity a) (eam-session-list--activity b)))
      (if (and (numberp av) (numberp bv)) (> av bv)
        (string< (format "%s" av) (format "%s" bv))))))
(defun eam-session-list--text (value width)
  (truncate-string-to-width
   (replace-regexp-in-string "[[:cntrl:]]" " " (format "%s" value)) width nil nil "…"))
(defun eam-session-list--date (value)
  (if (> value 0) (format-time-string "%m-%d %H:%M:%S" (seconds-to-time value)) "—"))
(defun eam-session-list--row (entry)
  (let* ((notices (alist-get 'notifications entry))
         (seq (alist-get 'seq notices))
         (start (point)))
    (insert (format "  %-26s %-7s %-8s %-7s %-14s  %-14s  %s%s\n"
                    (eam-session-list--text (eam-session-list--label entry) 26)
                    (eam-session-list--text (alist-get 'provider entry) 7)
                    (eam-session-list--state entry)
                    (cond ((eam-session-list--unread entry) "NEW")
                          ((and (numberp seq) (> seq 0)) "read")
                          ((null notices) "unknown") (t "—"))
                    (eam-session-list--date (eam-session-list--activity entry))
                    (eam-session-list--date (eam-session-list--time entry 'created_at))
                    (if eam-session-list--group ""
                      (concat (eam-session-list--text
                               (abbreviate-file-name (eam-session-list--directory entry)) 120) " | "))
                    (eam-session-list--text
                     (file-name-nondirectory (eam-session-list--path entry)) 80)))
    (add-text-properties start (point) `(eam-session ,entry mouse-face highlight))))
(defun eam-session-list--render (&optional selected)
  (let* ((selected (or selected (eam-session-list--path (eam-session-list--at-point))))
         (inhibit-read-only t)
         (entries (sort (cl-remove-if
                         (lambda (e) (and eam-session-list--detached
                                          (not (equal (eam-session-list--state e) "detached"))))
                         (copy-sequence eam-session-list--entries))
                        #'eam-session-list--less)) groups)
    (erase-buffer)
    (insert (format "EAM sessions · %d active · %d unverified · sort: %s · %s\n"
                    (length entries) eam-session-list--unknown eam-session-list--sort
                    (if eam-session-list--detached "detached only" "all active")))
    (insert "RET open/read · g refresh · s sort · r rename · m mark read · t group · f filter · q close\n")
    (insert "\n  Name                       Provider State    Notice  Last PTY I/O    Created         ID / directory\n")
    (if (null entries) (insert "\nNo active sessions in this view.\n")
      (if (not eam-session-list--group) (mapc #'eam-session-list--row entries)
        (dolist (entry entries)
          (let* ((dir (eam-session-list--directory entry)) (group (assoc dir groups)))
            (if group (setcdr group (cons entry (cdr group)))
              (push (list dir entry) groups))))
        (dolist (group (nreverse groups))
          (insert "\n" (propertize (eam-session-list--text (abbreviate-file-name (car group)) 160)
                                   'face 'bold) "\n")
          (mapc #'eam-session-list--row (nreverse (cdr group))))))
    (goto-char (point-min))
    (let (first found)
      (while (and (not found) (< (point) (point-max)))
        (when-let ((entry (eam-session-list--at-point)))
          (unless first (setq first (point)))
          (when (equal selected (eam-session-list--path entry)) (setq found (point))))
        (unless found (forward-line 1)))
      (goto-char (or found first (point-min))))
    (set-buffer-modified-p nil)))
(defun eam-session-list--refresh ()
  (let ((inventory (eam-app--live-inventory)))
    (setq eam-session-list--entries (alist-get 'sessions inventory)
          eam-session-list--unknown (length (alist-get 'unverified inventory)))
    (eam-session-list--render)))
(defun eam-session-list--ack (entry)
  "Acknowledge only the snapshot sequence, leaving later events unread."
  (let ((seq (alist-get 'seq (alist-get 'notifications entry))))
    (when (and (integerp seq) (> seq 0))
      (eam-notifications--acknowledge (eam-session-list--path entry) seq))))
(defun eam-session-list--open ()
  (let* ((entry (or (eam-session-list--at-point) (user-error "Select a session row")))
         (path (eam-session-list--path entry))
         (buffer (current-buffer))
         (existing (cl-find-if
                    (lambda (s)
                      (and (buffer-live-p (eam-terminal-output s))
                           (process-live-p (eam-terminal-process s))
                           (equal (directory-file-name path)
                                  (when-let ((p (buffer-local-value 'eam-terminal-persistent-directory
                                                                    (eam-terminal-output s))))
                                    (directory-file-name p))))) eam-terminal--sessions)))
    (if existing (pop-to-buffer (eam-terminal-output existing))
      (if (equal (eam-session-list--state entry) "detached") (eam-attach path)
        (user-error "Session is attached in another Emacs; detach it there first")))
    (eam-session-list--ack entry)
    (with-current-buffer buffer (eam-session-list--refresh))))
(defun eam-session-list--sort-select ()
  (setq eam-session-list--sort
        (intern (completing-read "Sort sessions: "
                                 '("activity" "created" "directory" "name" "provider" "state" "unread")
                                 nil t nil nil (symbol-name eam-session-list--sort))))
  (eam-session-list--render))
;;;###autoload
(defun eam-rename (name)
  "Persist NAME for the selected session.  Empty NAME restores automatic naming."
  (interactive (list (read-string "Session name (empty = automatic): "
                                  (alist-get 'name (eam-session-list--at-point)))))
  (let* ((entry (eam-session-list--at-point))
         (path (or (eam-session-list--path entry)
                   eam-terminal-persistent-directory
                   (and eam-terminal--current
                        (buffer-live-p (eam-terminal-output eam-terminal--current))
                        (buffer-local-value 'eam-terminal-persistent-directory
                                            (eam-terminal-output eam-terminal--current)))
                   (user-error "Use a session list, CLI or draft buffer")))
         (metadata (eam-persistent--call "rename" `((session . ,path) (name . ,name)))))
    (dolist (s eam-terminal--sessions)
      (when (and (buffer-live-p (eam-terminal-output s))
                 (equal (directory-file-name path)
                        (when-let ((p (buffer-local-value 'eam-terminal-persistent-directory
                                                          (eam-terminal-output s))))
                          (directory-file-name p))))
        (eam-persistent--set-label s (alist-get 'name metadata))))
    (when (derived-mode-p 'eam-session-list-mode) (eam-session-list--refresh))
    (message "Session name saved")))
(defvar eam-session-list-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "RET") (lambda () (interactive) (eam-session-list--open)))
    (define-key map (kbd "g") (lambda () (interactive) (eam-session-list--refresh)))
    (define-key map (kbd "s") (lambda () (interactive) (eam-session-list--sort-select)))
    (define-key map (kbd "r") #'eam-rename)
    (define-key map (kbd "m") (lambda () (interactive)
                                (eam-session-list--ack (or (eam-session-list--at-point)
                                                          (user-error "Select a session row")))
                                (eam-session-list--refresh)))
    (define-key map (kbd "t") (lambda () (interactive)
                                (setq eam-session-list--group (not eam-session-list--group))
                                (eam-session-list--render)))
    (define-key map (kbd "f") (lambda () (interactive)
                                (setq eam-session-list--detached (not eam-session-list--detached))
                                (eam-session-list--render)))
    map))
(define-derived-mode eam-session-list-mode special-mode "EAM Sessions"
  "Active persistent sessions grouped by directory.  See the buffer's key guide."
  (setq truncate-lines t)
  (buffer-disable-undo))
(put 'eam-session-list-mode 'completion-predicate #'ignore)
;;;###autoload
(defun eam-sessions (&optional detached-only)
  "Show active sessions.  With prefix DETACHED-ONLY, show detached sessions only."
  (interactive "P")
  (require 'eam-app)
  (let ((directory default-directory))
    (pop-to-buffer (get-buffer-create "*EAM sessions*"))
    (unless (derived-mode-p 'eam-session-list-mode)
      (eam-session-list-mode)
      (setq eam-session-list--sort eam-session-sort-order
            eam-session-list--group eam-session-group-by-directory))
    (setq default-directory directory eam-session-list--detached detached-only)
    (eam-session-list--refresh)))
(declare-function eam-app--live-inventory "eam-app" ())
(provide 'eam-session-list)
;;; eam-session-list.el ends here
