;;; session-list-test.el --- Session management regressions -*- lexical-binding: t; -*-
(require 'ert)
(require 'eam-app)
(defun eam-list-test-entry (id directory name activity &optional unread)
  `((session . ,(concat "/tmp/" id)) (directory . ,directory) (name . ,name)
    (provider . "Codex") (attached_clients . 0) (created_at . 10)
    (last_input_at . ,activity) (last_output_at . 0)
    (notifications . ((seq . 2) (read_seq . ,(if unread 0 2)) (unread . ,unread)))))

(ert-deftest eam-list-prefill-and-name-flow ()
  (let ((default-directory "/tmp/한글 프로젝트/") (insert-default-directory nil) calls)
    (cl-letf (((symbol-function 'eam--read-provider) (lambda () "Codex"))
              ((symbol-function 'read-directory-name)
               (lambda (_ dir default mustmatch initial &rest _)
                 (should (equal dir default-directory))
                 (should (equal default default-directory))
                 (should (equal initial default-directory)) (should mustmatch) initial))
              ((symbol-function 'read-string) (lambda (&rest _) "새 작업"))
              ((symbol-function 'eam-persistent--start)
               (lambda (provider directory args &optional name)
                 (push (list provider directory args name) calls) (eam-terminal--session))))
      (call-interactively #'eam-new)
      (call-interactively #'eam-resume)
      (should (equal (reverse calls)
                     '(("Codex" "/tmp/한글 프로젝트/" nil "새 작업")
                       ("Codex" "/tmp/한글 프로젝트/" ("resume") "새 작업")))))))

(ert-deftest eam-list-groups-sorts-filter-and-selection ()
  (with-temp-buffer
    (eam-session-list-mode)
    (setq eam-session-list--entries
          (list (eam-list-test-entry "a" "/tmp/project/" "같은 이름" 20)
                (eam-list-test-entry "b" "/tmp/project" "같은 이름" 30)
                (eam-list-test-entry "c" "/tmp/other" "다른 이름" 40 t))
          eam-session-list--sort 'activity eam-session-list--group t)
    (eam-session-list--render)
    (should (eq buffer-undo-list t))
    (should (equal (eam-session-list--path (eam-session-list--at-point)) "/tmp/c"))
    (should (= 1 (how-many "^/tmp/project$" (point-min) (point-max))))
    (dolist (order '(activity created directory name provider state unread))
      (setq eam-session-list--sort order)
      (eam-session-list--render "/tmp/b")
      (should (equal (eam-session-list--path (eam-session-list--at-point)) "/tmp/b")))
    (setq eam-session-list--sort 'unread)
    (should (equal (mapcar #'eam-session-list--path
                          (sort (copy-sequence eam-session-list--entries) #'eam-session-list--less))
                   '("/tmp/c" "/tmp/b" "/tmp/a")))
    (should (string-match-p "NEW" (buffer-string)))
    (should (string-match-p "read" (buffer-string)))
    (setf (alist-get 'attached_clients (car eam-session-list--entries)) 1)
    (setq eam-session-list--detached t)
    (eam-session-list--render)
    (should-not (string-match-p "  a\n" (buffer-string)))))

(ert-deftest eam-list-open-does-not-acknowledge-failed-attachment ()
  (with-temp-buffer
    (eam-session-list-mode)
    (setq eam-session-list--entries (list (eam-list-test-entry "a" "/tmp" "" 0 t))
          eam-session-list--sort 'activity)
    (eam-session-list--render)
    (let ((eam-terminal--sessions nil))
      (cl-letf (((symbol-function 'eam-attach) (lambda (&rest _) (user-error "Unavailable")))
                ((symbol-function 'eam-notifications--acknowledge)
                 (lambda (&rest _) (ert-fail "Read without successful visit"))))
        (should-error (eam-session-list--open) :type 'user-error)))))

(ert-deftest eam-list-acknowledges-snapshot-only ()
  (let* ((entry (eam-list-test-entry "a" "/tmp" "" 0 t))
         (old (eam-notice--make :session "/tmp/a" :sequence 2))
         (new (eam-notice--make :session "/tmp/a" :sequence 3))
         (eam-notifications--entries (list new old)))
    (cl-letf (((symbol-function 'eam-persistent--call)
               (lambda (op request)
                 (should (equal op "acknowledge"))
                 (should (= (alist-get 'seq request) 2))
                 '((seq . 3) (read_seq . 2) (unread . t)))))
      (eam-session-list--ack entry)
      (should (eam-notice-read old))
      (should-not (eam-notice-read new)))))

(ert-deftest eam-list-rename-keeps-provider-identity-and-draft-undo ()
  (let* ((out (generate-new-buffer " *eam-name-output*"))
         (draft (generate-new-buffer " *eam-name-draft*"))
         (s (eam-terminal--session :name "Codex" :directory "/tmp/project/"
                                   :input draft :output out :resume-id "same-id"))
         (eam-terminal--sessions (list s)))
    (unwind-protect
        (progn
          (with-current-buffer out (setq-local eam-terminal-persistent-directory "/tmp/session"))
          (with-current-buffer draft
            (setq-local eam-terminal--current s)
            (buffer-enable-undo) (insert "수정 중")
            (let ((undo buffer-undo-list))
              (cl-letf (((symbol-function 'eam-persistent--call)
                         (lambda (op q)
                           (should (equal op "rename"))
                           (should (equal (alist-get 'session q) "/tmp/session"))
                           '((name . "이름 변경")))))
                (eam-rename "이름 변경"))
              (should (eq undo buffer-undo-list))
              (should (buffer-modified-p))
              (should (equal (buffer-string) "수정 중"))))
          (should (equal (eam-terminal-name s) "Codex"))
          (should (equal (eam-terminal-resume-id s) "same-id"))
          (should (string-match-p "이름 변경" (buffer-name out)))
          (should (string-match-p "이름 변경" (buffer-name draft))))
      (kill-buffer out) (with-current-buffer draft (set-buffer-modified-p nil)) (kill-buffer draft))))

(ert-deftest eam-list-bounded-render-256-sessions ()
  (with-temp-buffer
    (eam-session-list-mode)
    (setq eam-session-list--sort 'activity eam-session-list--group t
          eam-session-list--entries
          (cl-loop for i below 256 collect
                   (eam-list-test-entry (format "session-%d" i)
                                        (format "/tmp/project-%d/" (% i 32))
                                        (make-string 128 ?한) i)))
    (let ((started (float-time)))
      (dotimes (_ 10) (eam-session-list--render))
      (message "Session list: 256 sessions, 32 groups, 10 renders %.3fs, %d chars"
               (- (float-time) started) (buffer-size)))
    (should (< (buffer-size) 100000))
    (should (eq buffer-undo-list t))))

(ert-deftest eam-list-notice-restart-restores-read-state ()
  (let* ((dir (make-temp-file "eam-notice-read-" t))
         (file (expand-file-name "events.jsonl" dir))
         (buffer (generate-new-buffer " *eam-notice-restart*"))
         (eam-notifications--entries nil)
         (eam-notification-desktop nil))
    (unwind-protect
        (progn
          (with-temp-file file
            (insert "{\"version\":1,\"seq\":1,\"title\":\"완료\",\"body\":\"첫 응답\"}\n")
            (insert "{\"version\":1,\"seq\":2,\"title\":\"완료\",\"body\":\"새 응답\"}\n"))
          (with-temp-file (expand-file-name "notification-read.json" dir)
            (insert "{\"seq\":1}"))
          (let ((reader (eai-event-reader--create file buffer)))
            (eai-event-reader-poll reader)
            (should (= (length eam-notifications--entries) 2))
            (should-not (eam-notice-read (car eam-notifications--entries)))
            (should (eam-notice-read (cadr eam-notifications--entries)))
            (should (equal (eam-notice-session (car eam-notifications--entries)) dir))
            (eai-event-reader-poll reader)
            (should (= (length eam-notifications--entries) 2))))
      (kill-buffer buffer) (delete-directory dir t))))
